# #############################################################################
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ include "tap74-registry.fullname" . }}
  labels:
    {{- include "tap74-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tap74-registry.selectorLabels" . | nindent 4 }}
