# #############################################################################
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

replicaCount: 1

image:
  repository: ghcr.io/adtorales/tap74-registry
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8181
  targetPort: 8181

registry:
  url: "http://tap74-registry:8181/api/registry"
  oci:
    images: ""
    pollSeconds: 60
    insecure: false
    username: ""
    password: ""
  existingSecret: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

probes:
  liveness:
    path: /registry
    port: 8181
    initialDelaySeconds: 30
    periodSeconds: 30
  readiness:
    path: /registry
    port: 8181
    initialDelaySeconds: 10
    periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
